name: chop_gang
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.11.0
  flutter: ^3.41.0

dependencies:
  bloc: ^9.2.0
  dio: ^5.9.2
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.4
  flutter_secure_storage: ^10.3.1
  go_router: ^17.2.1
  get_it: ^9.2.1
  http: ^1.6.0
  intl: ^0.20.2
  pinput: ^6.0.2
  shared_preferences: ^2.5.5


dev_dependencies:
  bloc_lint: ^0.4.1
  bloc_test: ^10.0.0
  bloc_tools: ^0.1.0-dev.24
  build_runner: ^2.13.1
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  go_router_builder: ^4.2.1
  mocktail: ^1.0.5
  very_good_analysis: ^10.3.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  fonts:
    - family: Nectarine DEMO
      fonts:
        - asset: fonts/nectarine-demo.regular.otf
    - family: Supreme
      fonts:
        - asset: fonts/supreme/Supreme-Regular.otf
        - asset: fonts/supreme/Supreme-Bold.otf
        - asset: fonts/supreme/Supreme-Medium.otf
        - asset: fonts/supreme/Supreme-Light.otf
        - asset: fonts/supreme/Supreme-Italic.otf
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Black.otf
        - asset: fonts/satoshi/Satoshi-BlackItalic.otf
        - asset: fonts/satoshi/Satoshi-Bold.otf
        - asset: fonts/satoshi/Satoshi-BoldItalic.otf
        - asset: fonts/satoshi/Satoshi-Italic.otf
        - asset: fonts/satoshi/Satoshi-LightItalic.otf
        - asset: fonts/satoshi/Satoshi-Medium.otf
        - asset: fonts/satoshi/Satoshi-MediumItalic.otf
        - asset: fonts/satoshi/Satoshi-Regular.otf
